Source Codes/survey/urls.py
from django.conf.urls import patterns, include, url
import views
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'simple_survey.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^survey/(?P<object_id>\d+)/$', views.survey_view, name = "survey-detail"),
    url(r'^$', views.index, name="root"),
    url(r'^survey_fill/$', views.survey_fill, name= "fill-survey"),
    url(r'^survey_load/$', views.load_survey, name= "load-survey"),
    url(r'^admin_login/$', views.admin_login, name= "admin-login"),
    url(r'^admin_panel/$', views.admin_panel, name= "admin-panel"),
    url(r'^admin_panel/survey/(?P<survey_id>\d+)/$', views.admin_answers , name = "answer-detail"),
    url(r'^admin_panel/survey_create_view/$', views.survey_create_view, name= "admin-survey-create-view"),
    url(r'^admin_panel/survey_create/$', views.survey_create, name= "admin-survey-create"),
    url(r'^admin_panel/question_add_view/$', views.question_add_view, name= "admin-question-add-view"),
    url(r'^admin_panel/question_add/$', views.question_add, name= "admin-question-add"),
    url(r'^admin_panel/choice_add_view/$', views.choice_add_view, name= "admin-choice-add-view"),
    url(r'^admin_panel/choice_add/$', views.choice_add, name= "admin-choice-add"),
    url(r'^admin_panel/survey_delete/$', views.survey_delete, name= "admin-survey-delete"),
)

Source Codes/survey/models.py
from django.db import models

# Create your models here.
class Survey(models.Model):
    title = models.CharField(max_length = 200)

class Question(models.Model):
    question_text = models.CharField(max_length = 900)
    survey = models.ForeignKey(Survey)

class Choice(models.Model):
    choice_text = models.TextField()
    question = models.ForeignKey(Question)


class SurveyAnswer(models.Model):
    orig_survey = models.ForeignKey(Survey)

class QuestionAnswer(models.Model):
    answer = models.ForeignKey(Choice)
    survey_answer = models.ForeignKey(SurveyAnswer)

Source Codes/survey/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from models import Survey, SurveyAnswer, QuestionAnswer, Choice, Question
from django.contrib.auth import authenticate, login
# Create your views here.

def index(request):
    ctx = {}
    return render(request, 'main.html', ctx)
def survey_view(request, object_id = None):
    try:
        survey = Survey.objects.get(id=object_id)
        questions = survey.question_set.all()
        ctx = {'survey': survey, 'questions': questions}
    except:
        return render(request, 'surveynotfound-error.html', {'sv_id': object_id})
    return render(request, 'survey-take.html', ctx )
def load_survey(request):
    sv_load = request.POST['survey_view']
    return redirect('survey-detail', object_id=sv_load)
def admin_login(request):
    admin_usname = request.POST['username']
    admin_password = request.POST['password']
    user = authenticate(username=admin_usname, password=admin_password)
    if user is not None:
        login(request, user)
        return redirect('admin-panel')
    return render(request, 'main.html', {'login':False})
def admin_panel(request):
    surveys = Survey.objects.all()
    ctx = {'surveys': surveys}
    return render(request, 'admin-panel.html', ctx)
def admin_answers(request, survey_id):
    survey = Survey.objects.get(id=survey_id)
    answers = survey.surveyanswer_set.all()
    ctx = {'answers': answers, 'survey': survey}
    return render(request, 'admin-survey-detail.html', ctx)

def survey_fill(request):
    ans = SurveyAnswer()
    orig_survey = Survey.objects.get(id=request.POST['survey_id'])
    ans.orig_survey = orig_survey
    ans.save()
    questions = orig_survey.question_set.all()
    for question in questions:
        qc  = request.POST['question'+str(question.id)]
        qa = QuestionAnswer()
        qa.answer = Choice.objects.get(id=int(qc))
        qa.survey_answer = ans
        qa.save()
    ans.save()
    return render(request, 'survey-complete.html', {})

def survey_create_view(request):
    return render(request, 'survey-create.html', {})
def survey_create(request):
    newSurvey = Survey()
    newSurvey.title = request.POST['survey_title']
    newSurvey.save()
    request.session['current_survey'] = newSurvey.id
    return redirect('admin-question-add-view')

def question_add_view(request):
    return render(request, 'question-add.html', {})

def question_add(request):
    survey_add = Survey.objects.get(id= int(request.session['current_survey']))
    new_question = Question()
    new_question.question_text = request.POST['question_text']
    survey_add.question_set.add(new_question)
    new_question.save()
    survey_add.save()
    request.session['current_question'] = new_question.id
    return redirect('admin-choice-add-view')

def choice_add_view(request):
    question = Question.objects.get(id=request.session['current_question'])
    return render(request, 'choice-add.html', {'question': question})

def choice_add(request):
    question = Question.objects.get(id=request.session['current_question'])
    newChoice = Choice()
    newChoice.choice_text = request.POST["choice_text"]
    question.choice_set.add(newChoice)
    newChoice.save()
    question.save()
    return redirect('admin-choice-add-view')

def survey_delete(request):
    survey = request.POST['sv_delete']
    sv_del = Survey.objects.get(id=int(survey))
    sv_del.delete()
    return redirect('admin-panel')

Source Codes/survey/templates/admin-panel.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 10%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	</style>
	   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href={% url 'root' %}>Survey Site</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href={% url 'admin-survey-create-view' %}>Add Survey</a></li>
            <li><a href="#">View Survey Data</a></li>
          </ul>
      </div>
    </div>

    <div class = "centerdv container">
    	    <div class = "page-header">
    			<h2>Survey Results</h2>
    		</div>
    		<div class="panel panel-default">
  <!-- Default panel contents -->

  <!-- Table -->
  <table class="table">
  	<thead>
  		<tr>
  			<th>Survey ID#</th>
  			<th>Survey Title</th>
  			<th>Answers</th>
        <th>Delete Survey</th>
  		</tr>
  	</thead>
  	<tbody>
  		{% for survey in surveys %}
  		<tr>
  			<td>{{survey.id}}</td>
  			<td>{{survey.title}}</td>
  			<td><a class = "btn btn-primary" href={% url 'answer-detail' survey.id %}>View Answers<a></td>
        <td>
          <form method = 'post' action = {% url 'admin-survey-delete' %}> 
            {% csrf_token %} 
            <input type = 'hidden' name = "sv_delete" value = {{survey.id}}> 
            <input type ="submit" class = "btn btn-danger" value= "Delete">
          </form>
        </td>
  		</tr>
  		{% endfor %}
  	</tbody>
  </table>
</div>
    </div>
   </body>
   </html>

Source Codes/survey/templates/admin-survey-detail.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 10%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	</style>
	   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href={% url 'root'%}>Survey Site</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href={% url 'admin-survey-create-view' %}>Add Survey</a></li>
            <li><a href={% url 'admin-panel'%}>View Survey Data</a></li>
          </ul>
      </div>
    </div>

    <div class = "centerdv container">
    	    <div class = "page-header">
    			<h2>{{survey.title}}</h2>
    		</div>
    <div class="panel panel-default">
       <table class="table">
    <thead>
      <tr>
        <th>Question ID#</th>
        <th>Question Title</th>
        <th>Answer</th>
      </tr>
    </thead>
    <tbody>
      {% for answer in answers %}
      
        
        {% for qa in answer.questionanswer_set.all %}
        <tr>
        <td>{{qa.answer.question.id}}</td>
        <td>{{qa.answer.question.question_text}}</td>
        <td>{{qa.answer.choice_text}}</td>
      </tr>
        {% endfor %}
     
      {% endfor %}
    </tbody>
  </table>
</body>
</html>

Source Codes/survey/templates/choice-add.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 10%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.centerform
	{
		margin-left: auto;
		margin-right: auto;
		width: 45%;
	}
	</style>
	   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href={% url 'root' %}>Survey Site</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Add Survey</a></li>
            <li><a href={% url 'admin-panel'%}>View Survey Data</a></li>
          </ul>
      </div>
    </div>

    <div class = "centerdv container">
    	<div class = "page-header">
    		<h2>Add a Choice to {{question.question_text}}</h2>
    	</div>
    	<br>
    	<form method = "post"  class = "centerform" action={% url 'admin-choice-add' %}>
        {% csrf_token %}
    		<b>Question Text</b>
    		<input type = "text" class = "form-control" name = "choice_text">
    		<br>
        <p>
    		<input type = "submit" class= "btn btn-info" value = "Save Choice and Add New">
        <a href = {% url 'admin-panel' %} class  = 'btn btn-success'>Finish (will not save current Choice)</a>
        <a href = {% url 'admin-question-add-view' %} class  = 'btn btn-primary'>New Question</a>
        </p>
    	</form>
</body>
</html>

Source Codes/survey/templates/main.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 5%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.idtextbox
	{
		margin-top: 5%;
		margin-bottom: 5%;
		width: 80%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.idbutton
	{
		width: 20%;
		text-align: center;
		margin-left: auto;
		margin-right: auto;
	}

	</style>
<div class="jumbotron container centerdv">
  <h1>Simple Survey Site</h1>
  <p>Take Surveys here</p>
  <p><a class="btn btn-primary btn-lg" role="button" data-toggle="modal" data-target="#surveyIDmodal">Take a Survey</a>
  <a class="btn btn-info btn-lg" role="button" data-toggle="modal" data-target="#adminLoginModal">Admin Login</a></p>
  		{% if login == False %}
  		<div class="alert alert-danger alert-dismissible" role="alert">
  			  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
  			  	<span class="sr-only">Close</span></button>
  			  	Bad Login
  		</div>
  		{% endif %}
</div>
	
<div class="modal fade" role="dialog" id = "surveyIDmodal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    <div class="modal-header">
  		<h4>Enter a survey ID#</h4>
  	</div>
  	<form method = "post" class = "idtextbox" action = {% url 'load-survey'%}>
  		{% csrf_token %}
      <input type = "text" class = "form-control" name = "survey_view">
      <br>
      <input type = "submit" class = "btn btn-success" value = "Go!">
    </form>
    </div>
  </div>
</div>

<div class="modal fade" role="dialog" id = "adminLoginModal">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
    <div class="modal-header">
  		<h4>Login an Admin User</h4>
  	</div>
  	<form method = "post" class = "idtextbox" action = {% url 'admin-login'%}>
  		{% csrf_token %}
  		<b>Username:</b>
      <input type = "text" class = "form-control" name = "username">
      <br>
      <b>Password</b>
      <input type = "password" class = "form-control" name = "password">
      <br>
      <input type = "submit" class = "btn btn-success" value = "Login">
    </form>
    </div>
  </div>
</div>
</body>
</html>

Source Codes/survey/templates/question-add.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 10%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.centerform
	{
		margin-left: auto;
		margin-right: auto;
		width: 45%;
	}
	</style>
	   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href={% url 'root' %}>Survey Site</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Add Survey</a></li>
            <li><a href={% url 'admin-panel'%}>View Survey Data</a></li>
          </ul>
      </div>
    </div>

    <div class = "centerdv container">
    	<div class = "page-header">
    		<h2>Add a question</h2>
    	</div>
    	<br>
    	<form method = "post"  class = "centerform" action={% url 'admin-question-add' %}>
        {% csrf_token %}
    		<b>Question Text</b>
    		<input type = "text" class = "form-control" name = "question_text">
    		<br>
        <p>
    		<input type = "submit" class= "btn btn-primary" value = "Complete and Add Choices">
        </p>
    	</form>
</body>
</html>

Source Codes/survey/templates/survey-complete.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 5%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}

	</style>
<div class="jumbotron container centerdv">
  <h1>Survey Complete!</h1>
   <a class="btn btn-info btn-lg" role="button" href="/" >Return to the Main Page!</a></p>
</div>
</body>
</html>

Source Codes/survey/templates/survey-create.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 10%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.centerform
	{
		margin-left: auto;
		margin-right: auto;
		width: 45%;
	}
	</style>
	   <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href={% url 'root' %}>Survey Site</a>
        </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Add Survey</a></li>
            <li><a href={% url 'admin-panel'%}>View Survey Data</a></li>
          </ul>
      </div>
    </div>

    <div class = "centerdv container">
    	<div class = "page-header">
    		<h2> Create a new Survey</h2>
    	</div>
    	<br>
    	<form method = "post"  class = "centerform" action={% url 'admin-survey-create' %}>
    		{% csrf_token %}
    		<b>Survey Title</b>
    		<input type = "text" class = "form-control" name = "survey_title">
    		<br>
    		<input type = "submit" class= "btn btn-primary" value = "Add Questions">
    	</form>
</body>
</html>

Source Codes/survey/templates/survey-take.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.header-top
	{
		margin-top: 5%;
	}
	</style>
	<div class = "jumbotron container centerdv header-top">
		<h2>{{survey.title}}</h2>
	</div>
	<form method = "post" action = {% url 'fill-survey' %}>
	<input type = "hidden" name = "survey_id" value = {{survey.id}}>
	{% csrf_token %}
	{% for question in questions %}
	<div class = "container centerdv">
		<div class = "well page-header">
			<b>{{question.question_text}}</b>
		</div>

		{% for choice in question.choice_set.all %}
	    <label class="radio inline">
            <input type="radio" name ="question{{question.id}}" value={{choice.id}}>
            {{choice.choice_text}}
        </label>
        {% endfor %}




	{% endfor %}
	        <input type = "submit" value = "Complete!" class = "btn btn-lg btn-success">
    </form>
    	</div>
	</div>

	</body>
	</html>

Source Codes/survey/templates/surveynotfound-error.html
<html>
<head>
	<script src= "http://code.jquery.com/jquery-2.1.1.js"> </script>
	<link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet">
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>
	<style type = "text/css">
	.centerdv
	{
		margin-top: 5%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.idtextbox
	{
		margin-top: 5%;
		margin-bottom: 5%;
		width: 80%;
		margin-left: auto;
		margin-right: auto;
		text-align: center;
	}
	.idbutton
	{
		width: 20%;
		text-align: center;
		margin-left: auto;
		margin-right: auto;
	}

	</style>
<div class="jumbotron container centerdv">
  <h1>No Survey Here!</h1>
  <p>Survey # {{sv_id}} doesn't exist, try another ID</p>
 </div>
 </body>
 </html>